name = "MIRTjim"
uuid = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
authors = ["Jeff Fessler <fessler@umich.edu> and contributors"]
version = "0.25"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FFTViews = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
AxisArrays = "0.4.4, 0.4.6"
ColorTypes = "0.11, 0.12"
FFTViews = "0.3"
MosaicViews = "0.3"
OffsetArrays = "1.12"
Plots = "1.38"
REPL = "1.11"
julia = "1.12"
